// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"GinStart/Ioc"
	"GinStart/Repository"
	"GinStart/Repository/Cache"
	"GinStart/Repository/Dao"
	"GinStart/Service"
	"GinStart/Web"
	"GinStart/Web/Jwt"
	"github.com/gin-gonic/gin"
)

import (
	_ "github.com/spf13/viper/remote"
)

// Injectors from wire.go:

func InitWireServer() *gin.Engine {
	cmdable := Ioc.InitRedis()
	handler := Jwt.NewRedisJWTHandler(cmdable)
	logger := Ioc.InitLogger()
	v := Ioc.InitMiddleWare(cmdable, handler, logger)
	db := Ioc.InitDB(logger)
	userDao := Dao.NewUserDao(db)
	userCache := Cache.NewUserCache(cmdable)
	userRepository := Repository.NewCacheUserRepository(userDao, userCache)
	userService := Service.NewUserService(userRepository, logger)
	codeCache := Cache.NewCodeCache(cmdable)
	codeRepository := Repository.NewCodeRepository(codeCache)
	service := Ioc.InitSMSService()
	codeService := Service.NewCodeService(codeRepository, service)
	userHandler := Handler.NewUserHandler(userService, codeService, handler)
	wechatService := Ioc.InitWechatService()
	oAuth2WechatHandler := Handler.NewOAuth2WechatHandler(wechatService)
	engine := Ioc.InitWebServer(v, userHandler, oAuth2WechatHandler)
	return engine
}
