apiVersion: v1
kind: PersistentVolume
metadata:
  name: ginstart-mysql-pvc
spec:
#  这个标签一定要和 persistentVolumeClaim 中的匹配
  storageClassName: record
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
